✨ feat: add support for download course video (#119)
yutto-dev/yutto pull request #122
Opened 2023-04-05 16:30 UTC by JeasonKim

## 动机

支持对购买的课程类视频的下载

https://github.com/yutto-dev/yutto/issues/119

closes #119 

## 解决方案
仿造番剧类的视频的写法，主要改动点如下：
1. 增加了课程相关的api和extractor，并增加了对应的测试用例，以cheese命名。
2. yutto/__main__.py 、yutto/extractor/common.py 分别添加了加载和提取的逻辑
3. 修改了README.md的已支持的下载类型，增加了课程

## 类型

-  [x] :sparkles: feat: 添加新功能
-  [ ] :bug: fix: 修复 bug
-  [x] :pencil: docs: 对文档进行修改
-  [ ] :recycle: refactor: 代码重构（既不是新增功能，也不是修改 bug 的代码变动）
-  [ ] :zap: perf: 提高性能的代码修改
-  [ ] :technologist: dx: 优化开发体验
-  [ ] :hammer: workflow: 工作流变动
-  [ ] :label: types: 类型声明修改
-  [ ] :construction: wip: 工作正在进行中
-  [x] :white_check_mark: test: 测试用例添加及修改
-  [ ] :hammer: build: 影响构建系统或外部依赖关系的更改
-  [ ] :construction_worker: ci: 更改 CI 配置文件和脚本
-  [ ] :question: chore: 其它不涉及源码以及测试的修改
-  [ ] :arrow_up: deps: 依赖项修改
-  [ ] :bookmark: release: 发布新版本

2023-04-07 06:46 UTC, SigureMo commented on yutto/api/cheese.py
> +    is_section: bool  # 是否属于专区
课程也是有专区这种东西的是嘛？

2023-04-07 07:01 UTC, SigureMo commented on tests/test_api/test_cheese.py
> +@pytest.mark.ci_skip
番剧是因为 CI 上无法跑才 skip 的，这里 `get_cheese_playurl` 也是嘛？可以测试一下，如果可以通过就不要 skip 了

2023-04-07 15:49 UTC, SigureMo reviewed
> 以cheese命名。

这个是有什么来源的嘛？

2023-04-07 15:49 UTC, SigureMo commented on yutto/extractor/common.py
> +            metadata=None,
metadata 是否可以一并解析呢？

2023-04-07 15:49 UTC, SigureMo commented on yutto/extractor/common.py
> +            subtitles=[],
可以确定课程是没有 subtitles 的嘛？

2023-04-07 15:49 UTC, SigureMo commented on yutto/extractor/cheese_batch.py
> +    REGEX_SS_ID = re.compile(r"ss(?P<season_id>\d+)")
课程也是使用 ep 和 ss 嘛？按照 `extractors` 里的顺序，现在的逻辑会不会导致提前匹配到番剧呢？

2023-04-07 15:49 UTC, SigureMo commented on yutto/extractor/cheese_batch.py
> +    """番剧全集"""
这里没改

2023-04-08 13:55 UTC, JeasonKim commented on yutto/api/cheese.py
> +    is_section: bool  # 是否属于专区
我并不是很了解这个专区的概念是什么用途，课程类的下载我是仿造番剧写的。

2023-04-08 13:57 UTC, JeasonKim commented on tests/test_api/test_cheese.py
> +@pytest.mark.ci_skip
这个可以跑通的，可以不做skip

2023-04-08 14:02 UTC, JeasonKim commented on yutto/extractor/common.py
> +            metadata=None,
本来我是想一并解析的，但是发现metaData对应的属性好像并不能全部找到，去掉之后并不影响下载，所以暂时就先留空了

2023-04-08 14:03 UTC, JeasonKim commented on yutto/extractor/cheese_batch.py
> +    REGEX_SS_ID = re.compile(r"ss(?P<season_id>\d+)")
会的，所以我再readme中的案例只支持通过全域名匹配，而不能用简写匹配

2023-04-08 14:05 UTC, JeasonKim commented on yutto/extractor/cheese_batch.py
> +    """番剧全集"""
好的，这个我修改一下

2023-04-08 14:07 UTC, SigureMo commented on yutto/api/cheese.py
> +    is_section: bool  # 是否属于专区
可参考 https://github.com/yutto-dev/yutto/blob/main/yutto/api/bangumi.py#L64

专区是指非正传内容，主要是 PV 等的一些附加内容，目前默认是不会下载的，只有开启 `--with-section` 选项才会下载

2023-04-08 14:11 UTC, SigureMo commented on yutto/extractor/cheese_batch.py
> +    REGEX_SS_ID = re.compile(r"ss(?P<season_id>\d+)")
> 会的，所以我再readme中的示例中只支持通过全域名匹配，而不能用简写匹配

如果是这样的话，我们这里还需要 id 匹配的逻辑嘛？如果写了但是毫无作用会引起别人的困惑，可以选择：

1. 删掉，我们确定课程不支持 id 匹配
2. 保留，写上注释说明目前不支持，但会在未来以某种方式支持，但需要确定可行性

2023-04-08 14:12 UTC, SigureMo commented on yutto/extractor/common.py
> +            metadata=None,
> 但是发现metaData对应的属性好像并不能全部找到

不一定需要全部找到，番剧和投稿视频同样也有部分留空，如果主要信息都存在的话就可以先加上，避免这一功能的缺失

2023-04-12 10:25 UTC, JeasonKim commented on yutto/api/cheese.py
> +    is_section: bool  # 是否属于专区
理解了，那这个是不需要的。我会把这个定义和相关逻辑去掉

2023-04-12 11:25 UTC, JeasonKim commented on yutto/extractor/common.py
> +            subtitles=[],
我看了一下课程类的视频的subtitle值是都是这样的格式”视频课·7分6秒“，没有真正的实际用途，考虑暂时就不要了

2023-04-12 16:15 UTC, JeasonKim commented on yutto/extractor/cheese_batch.py
> +    REGEX_SS_ID = re.compile(r"ss(?P<season_id>\d+)")
选择了方案1，已经注释掉了，并添加了注释

2023-04-12 16:15 UTC, JeasonKim commented
已经重新做了提交

2023-04-12 16:19 UTC, SigureMo commented
> 已经重新做了提交

麻烦看一下 CI 里的报错

2023-04-12 16:19 UTC, SigureMo commented on yutto/extractor/common.py
> +            subtitles=[],
了解

2023-04-12 16:28 UTC, SigureMo requested changes

2023-04-12 16:28 UTC, SigureMo commented on yutto/api/cheese.py
> +                "avid": BvId(item["aid"]),
首先需要确定这里我们得不到 BvId 是吗，在有 BvId 的情况下推荐使用 BvId

AvId 是 AId 和 BvId 的统合体，但不代表可以随便使用，这里是 AId 就应该用 AId，而不是 BvId

此外，所有 ID 需要传入 str，这里传入了 int，会导致报错：

```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Users/nyakku/Projects/yutto/yutto/__main__.py", line 54, in main
    run(args_list)
  File "/Users/nyakku/Projects/yutto/yutto/utils/funcutils/as_sync.py", line 34, in sync_func
    return asyncio.run(async_func(*args, **kwargs))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.11/3.11.3/Frameworks/Python.framework/Versions/3.11/lib/python3.11/asyncio/runners.py", line 190, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.11/3.11.3/Frameworks/Python.framework/Versions/3.11/lib/python3.11/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.11/3.11.3/Frameworks/Python.framework/Versions/3.11/lib/python3.11/asyncio/base_events.py", line 653, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/Users/nyakku/Projects/yutto/yutto/__main__.py", line 254, in run
    episode_data = await episode_data_coro
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/nyakku/Projects/yutto/yutto/extractor/common.py", line 94, in extract_cheese_data
    videos, audios = await get_cheese_playurl(session, avid, episode_id, cid)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/nyakku/Projects/yutto/yutto/api/cheese.py", line 78, in get_cheese_playurl
    raise NoAccessPermissionError(f"无法获取该视频链接（avid: {avid}, cid: {cid}），原因：{resp_json.get('message')}")
                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: __str__ returned non-string (type int)
sys:1: RuntimeWarning: coroutine 'extract_cheese_data' was never awaited
```

这里 raise 的时候触发了 `__str__` 及其返回类型强制检查，所以会报错

2023-04-12 16:28 UTC, SigureMo commented on yutto/extractor/common.py
> +            subtitles=[],  # 目前的值是"视频课·7分6秒"，并非子标题概念，没有实际价值暂时留空。
emmmm，subtitle 是指字幕，不是子标题……

2023-04-13 02:07 UTC, JeasonKim commented on yutto/extractor/common.py
> +            subtitles=[],  # 目前的值是"视频课·7分6秒"，并非子标题概念，没有实际价值暂时留空。
sorry ，是我望文生义和视频的副标题搞混了，课程类的也有subtitles的。但是我购买的2个的视频都没有单独的字幕，我看这个的数据结构和番剧是一样的，重新补充上去了。

2023-04-13 02:09 UTC, JeasonKim commented on yutto/api/cheese.py
> +                "avid": BvId(item["aid"]),
已修改，我本地走过test因为我是3.9的Python版本没有报错，所以本地没有发现这个问题

2023-04-13 03:21 UTC, SigureMo commented on yutto/api/cheese.py
> +    avid: AId
这里仍然应该是 AvId，因为这里应当支持 AId 和 BvId 两种形式，下面 59 行是针对具体情况而言的，应该使用 AId 和 BvId 其一

2023-04-13 03:21 UTC, SigureMo commented on tests/test_api/test_cheese.py
> +    # TODO: 暂未找到需要字幕的课程
这里是什么意思呢？未找到为什么上面会有测试内容呢？

2023-04-13 03:24 UTC, SigureMo commented on tests/test_api/test_cheese.py
> +@pytest.mark.ci_skip
这里确认下吧，看下 CI 的结果，应该也是不能跑的，注意我这里说的是 CI 环境不能跑，不是本地不能跑，因为 GitHub Actions 是在国外，部分 API 无法访问

2023-04-13 03:24 UTC, SigureMo commented on tests/test_api/test_cheese.py
> +@pytest.mark.ci_skip
以及 CI 里的 Lint and Format 报错也需要关注

2023-04-13 05:44 UTC, JeasonKim commented on tests/test_api/test_cheese.py
> +    # TODO: 暂未找到需要字幕的课程
测试内容是预留的范本，因为我的课程中没有找到需要字幕的，空跑一下看看逻辑是否存在问题。如果后续有类似视频了，可以把断言补全

2023-04-13 05:46 UTC, JeasonKim commented
> > 已经重新做了提交
> 
> 麻烦看一下 CI 里的报错

请问我有什么办法在我本地跑一下这几个版本的ci嘛,是安装多了Python版本切换着跑test吗？我本地的版本都问题，提交再看到会比较滞后

2023-04-13 05:59 UTC, SigureMo commented
> 请问我有什么办法在我本地跑一下这几个版本的ci嘛,是安装多了Python版本切换着跑test吗？我本地的版本都问题，提交再看到会比较滞后

目前的问题与 Python 版本无关，不需要切换版本即可复现

2023-04-13 15:50 UTC, merged