Feat add viewpoint
yutto-dev/yutto pull request #274
Opened 2024-06-03 20:02 UTC by Muffeter

## 动机
✨ 是否考虑添加章节信息 #248
在metadata中添加了章节信息

## 解决方案
参考了[kodi](https://kodi.wiki/view/NFO_files/Episodes)中nfo文件的格式
在 https://www.bilibili.com/video/BV1pV4y1R7p8 这样含章节时间点的视频的metadata里添加`episodebookmark`时间点:
```
<episodedetails>
  <actor>
    <name>绿导师原谅你了</name>
    <order>0</order>
    <profile>https://space.bilibili.com/202224425</profile>
    <role>UP主</role>
    <thumb>https://i2.hdslb.com/bfs/face/bc288c3544209fb2bdadaf45015721555175df17.jpg</thumb>
  </actor>
  <dateadded>2024-06-03 20:01:45</dateadded>
  <episodebookmark>
    <position>739</position>
  </episodebookmark>
  <episodebookmark>
    <position>1842</position>
  </episodebookmark>
  <episodebookmark>
    <position>2559</position>
  </episodebookmark>
  <episodebookmark>
    <position>4352</position>
  </episodebookmark>
  <episodebookmark>
    <position>5802</position>
  </episodebookmark>
  <genre>计算机技术</genre>
  <original_filename></original_filename>
  <plot>2023 南京大学《操作系统：设计与实现》
  课程主页（含讲义）：https://jyywiki.cn/OS/2023/</plot>
  <premiered>2023-03-21</premiered>
  <show_title>同步：生产者-消费者与条件变量 (算法并行化；万能同步方法) [南京大学2023操作系统-P9] (蒋炎岩)</show_title>
  <source></source>
  <tag>汇编</tag>
  <tag>操作系统</tag>
  <tag>C语言</tag>
  <tag>编程</tag>
  <tag>条件变量</tag>
  <tag>同步</tag>
  <tag>南京大学</tag>
  <tag>并发</tag>
  <thumb>http://i1.hdslb.com/bfs/archive/54a6cf2b5cb45b427cae1703f7d464b932fdc428.jpg</thumb>
  <title>同步：生产者-消费者与条件变量 (算法并行化；万能同步方法) [南京大学2023操作系统-P9] (蒋炎岩)</title>
  <website>https://www.bilibili.com/video/BV1pV4y1R7p8</website>
</episodedetails>
```

## 类型

-  [x] :sparkles: feat: 添加新功能
-  [ ] :bug: fix: 修复 bug
-  [ ] :pencil: docs: 对文档进行修改
-  [ ] :recycle: refactor: 代码重构（既不是新增功能，也不是修改 bug 的代码变动）
-  [ ] :zap: perf: 提高性能的代码修改
-  [ ] :technologist: dx: 优化开发体验
-  [ ] :hammer: workflow: 工作流变动
-  [ ] :label: types: 类型声明修改
-  [ ] :construction: wip: 工作正在进行中
-  [ ] :white_check_mark: test: 测试用例添加及修改
-  [ ] :hammer: build: 影响构建系统或外部依赖关系的更改
-  [ ] :construction_worker: ci: 更改 CI 配置文件和脚本
-  [ ] :question: chore: 其它不涉及源码以及测试的修改
-  [ ] :arrow_up: deps: 依赖项修改
-  [ ] :bookmark: release: 发布新版本

2024-06-04 17:13 UTC, SigureMo commented
咦？#248 的需求好像是在生成的视频中用 FFmpeg 添加章节信息？而不是生成 nfo？

不过有了信息全都好说，可以和封面使用相同的逻辑，将章节信息存在 metadata 中，默认是会获取章节信息的，如果存在的话，会通过 FFmpeg 封装到视频元信息中，当用户传递 `--no-chapter-info` 的时候，不进行封装

2024-06-04 17:23 UTC, SigureMo requested changes

2024-06-04 17:23 UTC, SigureMo commented on yutto/api/ugc_video.py
> +    aid: AId
有了 `avid` 为什么还需要 `aid` 呢？

2024-06-04 17:23 UTC, SigureMo commented on yutto/api/ugc_video.py
> +    chapter_api = "https://api.bilibili.com/x/player/v2?cid={cid}&aid={aid}"
这个 API 是 `aid` 和 `bvid` 的统一 API 吧，可以参考获取 subtitle 时传递 `avid` 的方式

2024-06-04 17:23 UTC, SigureMo commented on yutto/api/ugc_video.py
> +    return chapters
```suggestion
    return [
        {"position": chapter_info["to"]}
        for chapter_info in raw_chapter_info
    ]
```

2024-06-04 17:23 UTC, SigureMo commented on yutto/processor/downloader.py
> +            metadata["episodebookmark"] = chapter
在这里往里面 set 很奇怪，这个信息应该在一开始就设置好的，不应该 mutable

2024-06-04 17:23 UTC, SigureMo commented on yutto/api/bangumi.py
> +        episodebookmark=[],  # TODO
```suggestion
        episodebookmark=[],  # There are no chapter info in bangumi for now
```

2024-06-04 17:23 UTC, SigureMo commented on yutto/api/cheese.py
> +        episodebookmark=[], # TODO
```suggestion
        episodebookmark=[], # There are no chapter info in cheese for now
```

2024-06-05 08:07 UTC, Muffeter commented on yutto/api/ugc_video.py
> +    chapter_api = "https://api.bilibili.com/x/player/v2?cid={cid}&aid={aid}"
是我糊涂了，这个api的cid是必须提供的，aid与bvid至少提供一个。我会修改它 :)

2024-06-07 19:45 UTC, SigureMo reviewed
另外可以也看一下 CI 中 lint-and-format 失败的问题～

2024-06-07 19:45 UTC, SigureMo commented on yutto/api/ugc_video.py
> +        chapter_data=[],
这里不用省这一个 API 了，可以和 `video_info`、`page_info` 一样，上层获取完信息之后可以直接传进来

另外 `is_first_page` 参数应该可以清理一下了，现在应该是没用的了～

2024-06-07 19:45 UTC, SigureMo commented on yutto/extractor/common.py
> +        chapters = await get_ugc_video_chapters(client, avid, cid) if args.require_chapter else []
同上，这个信息不需要在这个时候再传，`require_chapter` 只控制视频里是否封装，metadata 里还是需要它的

2024-06-07 19:45 UTC, SigureMo commented on yutto/processor/downloader.py
> +    command_builder.with_extra_options(["-map_metadata", "1"])
这里的 `"1"` 是不是不能硬编码？是否可以参考 cover 自适应呢？

2024-06-07 19:45 UTC, SigureMo commented on yutto/processor/downloader.py
> +
另外，生成的 `.ini` 用完是不是应该清除下？

2024-06-16 07:35 UTC, SigureMo approved these changes
LGTMeow <img src="https://www.gstatic.com/android/keyboard/emojikitchen/20231113/u1f4a1/u1f4a1_u1f43e.png" width="14" alt="🐾"/>

2024-06-16 07:37 UTC, merged